name: Release Electron App

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build/Release Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
        # The GH_TOKEN is automatically provided by GitHub Actions
        # No need to set it manually in repository secrets

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/*.exe
            out/*.blockmap
            out/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 